<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Dev10\Desktop\basic to expert C# education\Codes\New folder %282%29\TodoApp\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Dev10\Desktop\basic to expert C# education\Codes\New folder (2)\TodoApp\.editorconfig" />
  </ItemGroup>

</Project>
